### ISSUE TITLE
How do you make the audio loop?

### ISSUE THREAD

**Issue by tomast1337** [walllable/vmix-technologic#1]
I am trying to use VMix by looking this example but i couldn't figure out how to loop the audio

**Comment by tomast1337** [comment]
Nevermind, I managed to do it like in source 1 with Wavosaur

**Comment by walllable** [comment]
If you just want to loop the whole sound, you can also do this through the asset browser, I believe. Just right-click on the .vsnd file and click "enable looping". I dunno if it says exactly that, but it should mention compiling with looping somewhere there. This works on .wav and I believe .mp3
